#include "compiler/backend/trainer/kernel_emitter.h"

#include <algorithm>

namespace seeml::update {

namespace {

size_t ClampGpuDim(size_t v) {
  const size_t clamped = std::clamp<size_t>(v, 8, 32);
  return clamped - clamped % 8;
}

/// One tiled GEMM kernel body. The A/B index expressions are the only
/// difference between the transpose variants; `accumulate` switches the
/// final store between assignment and alpha-scaled accumulation.
std::string KernelBody(const GpuTiling& t, const std::string& name,
                       const std::string& a_index,
                       const std::string& b_index, bool accumulate) {
  const std::string tm = std::to_string(t.tile_m);
  const std::string tn = std::to_string(t.tile_n);
  const std::string tk = std::to_string(t.tile_k);

  std::string s;
  s += "kernel void " + name + "(\n";
  s += "    device const float* A [[buffer(0)]],\n";
  s += "    device const float* B [[buffer(1)]],\n";
  s += "    device float* C [[buffer(2)]],\n";
  s += "    constant SeemlGemmDims& dims [[buffer(3)]],\n";
  s += "    uint2 tid [[thread_position_in_threadgroup]],\n";
  s += "    uint2 gid [[thread_position_in_grid]]) {\n";
  s += "  threadgroup float a_tile[" + tm + "][" + tk + "];\n";
  s += "  threadgroup float b_tile[" + tk + "][" + tn + "];\n";
  s += "  const uint row = gid.y, col = gid.x;\n";
  s += "  float acc = 0.0f;\n";
  s += "  for (uint k0 = 0; k0 < dims.k; k0 += " + tk + ") {\n";
  s += "    // Stage the K-panel through threadgroup memory.\n";
  s += "    for (uint kk = tid.x; kk < " + tk + "; kk += " + tn + ") {\n";
  s += "      const uint k = k0 + kk;\n";
  s += "      a_tile[tid.y][kk] = (row < dims.m && k < dims.k)\n";
  s += "          ? A[" + a_index + "] : 0.0f;\n";
  s += "    }\n";
  s += "    for (uint kk = tid.y; kk < " + tk + "; kk += " + tm + ") {\n";
  s += "      const uint k = k0 + kk;\n";
  s += "      b_tile[kk][tid.x] = (col < dims.n && k < dims.k)\n";
  s += "          ? B[" + b_index + "] : 0.0f;\n";
  s += "    }\n";
  s += "    threadgroup_barrier(mem_flags::mem_threadgroup);\n";
  s += "    for (uint kk = 0; kk < " + tk + "; ++kk)\n";
  s += "      acc = fma(a_tile[tid.y][kk], b_tile[kk][tid.x], acc);\n";
  s += "    threadgroup_barrier(mem_flags::mem_threadgroup);\n";
  s += "  }\n";
  s += "  if (row < dims.m && col < dims.n)\n";
  if (accumulate)
    s += "    C[row * dims.n + col] += dims.alpha * acc;\n";
  else
    s += "    C[row * dims.n + col] = acc;\n";
  s += "}\n";
  return s;
}

}  // namespace

GpuTiling GpuTilingFromHost(const GemmTiling& host) {
  return {.tile_m = ClampGpuDim(host.mc),
          .tile_n = ClampGpuDim(host.nc),
          .tile_k = ClampGpuDim(host.kc)};
}

std::string EmitMetalKernels(const GpuTiling& tiling) {
  std::string s;
  s +=
      "// Generated by seeml-update-compile. GEMM-family training kernels\n"
      "// for the update program, threadgroup-tiled at " +
      std::to_string(tiling.tile_m) + "x" + std::to_string(tiling.tile_n) +
      " outputs, K in panels of " + std::to_string(tiling.tile_k) + ".\n";
  s += "#include <metal_stdlib>\n";
  s += "using namespace metal;\n\n";
  s += "struct SeemlGemmDims {\n";
  s += "  uint m;\n  uint n;\n  uint k;\n  float alpha;\n";
  s += "};\n\n";

  // C[m,n] = A[m,k] @ B[k,n]  — forward matmul.
  s += KernelBody(tiling, "seeml_matmul",
                  "row * dims.k + k", "k * dims.n + col",
                  /*accumulate=*/false);
  s += "\n";
  // C[m,n] = A[m,k] @ B[n,k]^T — the dX backward (matmul_nt).
  s += KernelBody(tiling, "seeml_matmul_nt",
                  "row * dims.k + k", "col * dims.k + k",
                  /*accumulate=*/false);
  s += "\n";
  // C[m,n] = A[k,m]^T @ B[k,n] — the dW backward (matmul_tn).
  s += KernelBody(tiling, "seeml_matmul_tn",
                  "k * dims.m + row", "k * dims.n + col",
                  /*accumulate=*/false);
  s += "\n";
  // C += alpha * A@B — the merge's delta accumulation (gemm_acc).
  s += KernelBody(tiling, "seeml_gemm_acc",
                  "row * dims.k + k", "k * dims.n + col",
                  /*accumulate=*/true);
  return s;
}

}  // namespace seeml::update
