#include "compiler/backend/trainer/native_emitter.h"

#include <filesystem>
#include <fstream>

#include "compiler/diagnostics/generating/error.h"
#include "source/parallel/parallel_for.h"

namespace seeml::update {

namespace generating = seeml::diag::generating;

namespace {

std::expected<void, std::string> WriteFile(const std::string& path,
                                           const std::string& content,
                                           bool executable = false) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f)
    return generating::FileError(generating::kNativeEmitter, "cannot write",
                                 path);
  f << content;
  // Close before the state check: with contents this small the whole file
  // can sit in the stream buffer, so a failed flush-at-close is the only
  // signal a truncated package would ever give.
  f.close();
  if (f.fail())
    return generating::FileError(generating::kNativeEmitter, "short write to",
                                 path);
  if (executable) {
    std::error_code ec;
    std::filesystem::permissions(path,
                                 std::filesystem::perms::owner_all |
                                     std::filesystem::perms::group_read |
                                     std::filesystem::perms::group_exec |
                                     std::filesystem::perms::others_read |
                                     std::filesystem::perms::others_exec,
                                 ec);
  }
  return {};
}

// Writes the plan as a decimal byte-array translation unit, streamed (E2,
// #81): the rendered text is ~4x the plan, and building it as per-chunk
// strings, concatenating them into one more string and only then writing
// held ~9x the plan resident at the peak. Here a bounded window of chunks
// renders in parallel, is written, and is reused — the peak is the plan
// plus a constant — and the file is character-identical to the old one.
//
// Manual decimal emission: a snprintf call per byte dominates emission
// time once plans reach megabytes (frozen weights live in the blob).
// Three digit appends and a comma beat the formatter by an order of
// magnitude and need no format-string parsing. Each byte's text (and its
// line break, keyed off the GLOBAL index) is independent of every other
// byte, so fixed chunks render in parallel and concatenate in order.
std::expected<void, std::string> WriteEmbeddedTU(
    const std::string& path, const std::vector<uint8_t>& plan) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f)
    return generating::FileError(generating::kNativeEmitter, "cannot write",
                                 path);
  f << "// Generated by seeml-update-compile. The compiled Update Plan as an\n"
       "// object-file byte array: instruction streams, memory layout, frozen\n"
       "// weights, and adapter initialization — the entire update, as data.\n"
       "#include <cstddef>\n\n"
       "extern const unsigned char kSeemlUpdatePlan[] "
       "__attribute__((aligned(64)));\n"
       "extern const size_t kSeemlUpdatePlanSize;\n\n"
       "const unsigned char kSeemlUpdatePlan[] __attribute__((aligned(64))) = "
       "{\n";
  constexpr size_t kEmbedGrain = 256 * 1024;  // plan bytes per chunk
  constexpr size_t kWindowChunks = 64;        // 16 MiB of plan per window
  std::vector<std::string> parts(kWindowChunks);
  for (std::string& part : parts) part.reserve(kEmbedGrain * 4 + 8);
  for (size_t base = 0; base < plan.size();
       base += kEmbedGrain * kWindowChunks) {
    const size_t window =
        std::min(plan.size() - base, kEmbedGrain * kWindowChunks);
    const size_t chunks = (window + kEmbedGrain - 1) / kEmbedGrain;
    // One ParallelFor item per chunk: the window's geometry is explicit,
    // never the pool's.
    ParallelFor(chunks, 1, [&](size_t c0, size_t c1, size_t) {
      for (size_t c = c0; c < c1; ++c) {
        std::string& out = parts[c];
        out.clear();
        const size_t begin = base + c * kEmbedGrain;
        const size_t end = std::min(begin + kEmbedGrain, base + window);
        for (size_t i = begin; i < end; ++i) {
          const unsigned v = plan[i];
          if (v >= 100) {
            out += static_cast<char>('0' + v / 100);
            out += static_cast<char>('0' + (v / 10) % 10);
            out += static_cast<char>('0' + v % 10);
          } else if (v >= 10) {
            out += static_cast<char>('0' + v / 10);
            out += static_cast<char>('0' + v % 10);
          } else {
            out += static_cast<char>('0' + v);
          }
          out += ',';
          if ((i + 1) % 24 == 0) out += '\n';
        }
      }
    });
    for (size_t c = 0; c < chunks; ++c)
      f.write(parts[c].data(), static_cast<std::streamsize>(parts[c].size()));
  }
  f << "\n};\nconst size_t kSeemlUpdatePlanSize = sizeof(kSeemlUpdatePlan);\n";
  f.close();
  if (f.fail())
    return generating::FileError(generating::kNativeEmitter, "short write to",
                                 path);
  return {};
}

constexpr const char* kMainTU = R"cpp(// Generated by seeml-update-compile.
// The on-device model update program: train LoRA adapters against local
// data, gate on held-out validation, merge deltas, commit durably.
#include <cerrno>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>

#include "runtime/engine/update_engine.h"
#include "runtime/feeder/dataset.h"

extern const unsigned char kSeemlUpdatePlan[];
extern const size_t kSeemlUpdatePlanSize;

namespace {

const char* Arg(int argc, char** argv, const char* flag, const char* dflt) {
  for (int i = 1; i + 1 < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return argv[i + 1];
  return dflt;
}

bool Has(int argc, char** argv, const char* flag) {
  for (int i = 1; i < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return true;
  return false;
}

bool ParseU64(const char* s, uint64_t* out) {
  errno = 0;
  char* end = nullptr;
  const unsigned long long v = std::strtoull(s, &end, 10);
  if (errno != 0 || end == s || *end != '\0' || *s == '-') return false;
  *out = v;
  return true;
}

bool ParseF64(const char* s, double* out) {
  errno = 0;
  char* end = nullptr;
  const double v = std::strtod(s, &end);
  if (errno != 0 || end == s || *end != '\0') return false;
  *out = v;
  return true;
}

constexpr const char* kUsage =
    "usage: model_update --model <source.smf> --data <corpus.sds>"
    " [--out updated.smf] [--steps N] [--seed S]"
    " [--val-frac F] [--checkpoint ckpt] [--checkpoint-every N]"
    " [--resume] [--loss-log curve.csv] [--backend cpu|metal|auto]"
    " [--min-improvement F] [--require-accuracy] [--report report.json]"
    " [--force] [--help]\n"
    "  --min-improvement F: commit only if the gated loss fell by at least\n"
    "  the fraction F of its initial value (default 0: any strict fall).\n"
    "  --require-accuracy: additionally require held-out accuracy not to\n"
    "  drop (class-label plans with a validation split only).\n"
    "  --report FILE: write the backend, the gate parameters, the loss and\n"
    "  accuracy pairs and the verdict as JSON.\n"
    "  --backend: the executor (default cpu, or $SEEML_BACKEND). cpu is the\n"
    "  bitwise-deterministic reference and builds anywhere; metal runs the\n"
    "  update on an Apple GPU (an error where none exists); auto takes the\n"
    "  GPU when present and says so, else cpu.\n";

/// Every argv slot must be a known flag or a known flag's value: the
/// compiler CLI treats unconsumed arguments as hard errors, and the device
/// runner follows the same rule — a typo'd --val-frc must not silently
/// train with the default.
bool ArgsOk(int argc, char** argv) {
  static const char* const kValueFlags[] = {
      "--model",      "--data",     "--out",
      "--steps",      "--seed",     "--val-frac",
      "--checkpoint", "--loss-log", "--checkpoint-every",
      "--backend",    "--min-improvement", "--report"};
  static const char* const kBoolFlags[] = {"--force", "--resume", "--help",
                                           "-h", "--require-accuracy"};
  for (int i = 1; i < argc; ++i) {
    // Empty argv slots are shell debris (a quoted-but-unset "$VAR"), not
    // typos: nothing can be misread from one, and the pre-strict runner
    // accepted them — rejecting them would break existing wrappers for
    // zero safety gain. They stay ignorable.
    if (argv[i][0] == '\0') continue;
    bool known = false;
    for (const char* f : kValueFlags) {
      if (std::strcmp(argv[i], f) != 0) continue;
      // A '-'-prefixed value is a flag that swallowed its neighbor
      // (`--out --force`), not a value: Arg() would take it as a filename
      // while Has() independently still sees it as set. No legitimate
      // value here starts with '-' (paths aside, and steps/seed/val-frac
      // reject negatives anyway), so refuse rather than double-read.
      if (i + 1 >= argc || argv[i + 1][0] == '-') {
        std::fprintf(stderr, "model_update: %s requires a value\n", argv[i]);
        return false;
      }
      known = true;
      ++i;
      break;
    }
    if (!known)
      for (const char* f : kBoolFlags)
        if (std::strcmp(argv[i], f) == 0) {
          known = true;
          break;
        }
    if (!known) {
      std::fprintf(stderr,
                   "model_update: unknown argument '%s' (see --help)\n",
                   argv[i]);
      return false;
    }
  }
  return true;
}

}  // namespace

int main(int argc, char** argv) {
  // Strictness before convenience: ArgsOk first, so `--out -h` is a
  // missing-value error rather than a help hit on a swallowed slot. After
  // it passes, every argv slot is a known flag or a non-flag value, and
  // Has()/Arg() below cannot double-read a slot.
  if (!ArgsOk(argc, argv)) return 2;
  if (Has(argc, argv, "--help") || Has(argc, argv, "-h")) {
    std::fputs(kUsage, stdout);
    return 0;
  }

  const std::string model = Arg(argc, argv, "--model", "");
  const std::string data = Arg(argc, argv, "--data", "");
  const std::string out = Arg(argc, argv, "--out", "updated_model.smf");
  const std::string loss_log = Arg(argc, argv, "--loss-log", "");
  const bool force = Has(argc, argv, "--force");

  uint64_t steps = 0, seed = 0;
  double val_frac = 0.1, min_improvement = 0.0;
  // The negated in-range form rejects NaN, which `< 0.0 || >= 1.0` lets
  // through — and a NaN val_frac silently disables the validation gate
  // (a NaN margin would silently pass it).
  if (!ParseU64(Arg(argc, argv, "--steps", "0"), &steps) ||
      !ParseU64(Arg(argc, argv, "--seed", "0"), &seed) ||
      !ParseF64(Arg(argc, argv, "--val-frac", "0.1"), &val_frac) ||
      !(val_frac >= 0.0 && val_frac < 1.0) ||
      !ParseF64(Arg(argc, argv, "--min-improvement", "0"), &min_improvement) ||
      !(min_improvement >= 0.0 && min_improvement < 1.0)) {
    std::fprintf(stderr, "invalid numeric argument\n");
    return 2;
  }
  const bool require_accuracy = Has(argc, argv, "--require-accuracy");
  const std::string report_path = Arg(argc, argv, "--report", "");

  if (model.empty() || data.empty()) {
    std::fputs(kUsage, stderr);
    return 2;
  }

  // The executor backend: the flag wins over $SEEML_BACKEND, which wins
  // over the cpu default. Selected before the plan loads, so the load
  // binds the arena to the backend that will execute it.
  const char* backend_env = std::getenv("SEEML_BACKEND");
  const std::string backend_text =
      Arg(argc, argv, "--backend",
          backend_env && *backend_env ? backend_env : "cpu");
  const auto backend_kind =
      seeml::update_rt::ParseBackendKind(backend_text);
  if (!backend_kind) {
    std::fprintf(stderr,
                 "model_update: --backend (or $SEEML_BACKEND) must be cpu, "
                 "metal or auto, got '%s'\n",
                 backend_text.c_str());
    return 2;
  }
  // --require-accuracy needs something to measure: class labels (the eval
  // program's softmax) and a validation split. The plan header is right
  // here in the embedded bytes, so the usage error costs nothing — before
  // any backend is built or the plan hashed. A flag that cannot apply is a
  // usage error, never a silently vacuous gate.
  {
    seeml::update::PlanHeader hdr{};
    if (kSeemlUpdatePlanSize >= sizeof(hdr))
      std::memcpy(&hdr, kSeemlUpdatePlan, sizeof(hdr));
    if (require_accuracy && (hdr.label_kind != 1 || val_frac <= 0.0)) {
      std::fprintf(stderr,
                   "model_update: --require-accuracy needs a class-label plan "
                   "and a validation split (--val-frac > 0)\n");
      return 2;
    }
  }

  seeml::update_rt::UpdateEngine engine;
  if (auto r = engine.SelectBackend(*backend_kind); !r) {
    std::fprintf(stderr, "backend: %s\n", r.error().c_str());
    return 1;
  }
  if (!engine.backend_note().empty())
    std::fprintf(stderr, "seeml-update: %s\n", engine.backend_note().c_str());
  if (auto r = engine.LoadFromMemory(kSeemlUpdatePlan, kSeemlUpdatePlanSize); !r) {
    std::fprintf(stderr, "load: %s\n", r.error().c_str());
    return 1;
  }
  // The backend is recorded wherever results are compared (the per-backend
  // determinism doctrine): the banner, the gate line below, and the report.
  std::fprintf(stderr, "seeml-update: backend %s (%s)\n",
               engine.backend_name(), engine.backend_device().c_str());

  // Fail fast: the plan's emit offsets are only meaningful inside the exact
  // file it was compiled from, and commit would refuse anyway — but only
  // after the full training run. One file scan here buys that refusal now.
  if (auto r = engine.VerifySourceModel(model); !r) {
    std::fprintf(stderr, "model: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr,
               "seeml-update: resource contract — arena %llu bytes"
               " (%llu persistent)\n",
               (unsigned long long)engine.header().arena_size,
               (unsigned long long)engine.header().persistent_size);

  auto dataset = seeml::update_rt::Dataset::LoadFromFile(data);
  if (!dataset) {
    std::fprintf(stderr, "data: %s\n", dataset.error().c_str());
    return 1;
  }

  // Held-out validation split (before shuffling) drives the regression
  // gate; --val-frac 0 falls back to the training-loss trend.
  std::optional<seeml::update_rt::Dataset> val_set;
  if (val_frac > 0.0) {
    auto split = dataset->SplitValidation(val_frac);
    if (!split) {
      std::fprintf(stderr, "data: %s\n", split.error().c_str());
      return 1;
    }
    val_set = std::move(*split);
  }
  dataset->EnableShuffle(seed);

  seeml::update_rt::TrainOptions options;
  options.checkpoint_path = Arg(argc, argv, "--checkpoint", "");
  options.resume = Has(argc, argv, "--resume");
  options.validation = val_set ? &*val_set : nullptr;
  options.record_loss_curve = !loss_log.empty();
  if (!ParseU64(Arg(argc, argv, "--checkpoint-every", "0"),
                &options.checkpoint_every)) {
    std::fprintf(stderr, "invalid --checkpoint-every\n");
    return 2;
  }

  auto report = engine.Train(*dataset, steps, options);
  if (!report) {
    std::fprintf(stderr, "train: %s\n", report.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: train loss %.6f -> %.6f over %llu steps\n",
               report->initial_avg_loss, report->final_avg_loss,
               (unsigned long long)report->steps);
  if (report->has_validation)
    std::fprintf(stderr,
                 "seeml-update: validation loss %.6f -> %.6f [backend %s]\n",
                 report->val_initial_loss, report->val_final_loss,
                 engine.backend_name());
  if (report->has_val_accuracy)
    std::fprintf(stderr, "seeml-update: validation accuracy %.4f -> %.4f\n",
                 report->val_initial_accuracy, report->val_final_accuracy);

  if (!loss_log.empty()) {
    std::FILE* f = std::fopen(loss_log.c_str(), "w");
    if (f) {
      std::fprintf(f, "step,loss\n");
      for (size_t i = 0; i < report->loss_curve.size(); ++i)
        std::fprintf(f, "%zu,%.6f\n", i + 1, report->loss_curve[i]);
      std::fclose(f);
    }
  }

  // Regression gate: a failed update must leave the device untouched.
  // With a validation split this gates on held-out loss, not training
  // loss; --min-improvement demands a margin and --require-accuracy a
  // second, task-level opinion (#67). The verdict names the gate that
  // failed; the report is written last, so it records what actually
  // happened — including whether the commit landed.
  const bool loss_ok = report->ImprovedBy(static_cast<float>(min_improvement));
  const bool accuracy_measured = report->has_val_accuracy;
  const bool acc_ok =
      !require_accuracy || (accuracy_measured && report->AccuracyHeld());
  const bool accepted = loss_ok && acc_ok;
  const char* verdict = accepted ? "accepted" : (force ? "forced" : "rejected");
  std::fprintf(stderr,
               "seeml-update: gate min-improvement %.4g require-accuracy %s"
               " -> %s [backend %s]\n",
               min_improvement, require_accuracy ? "yes" : "no", verdict,
               engine.backend_name());
  auto write_report = [&](bool committed, const char* error) {
    if (report_path.empty()) return;
    std::FILE* f = std::fopen(report_path.c_str(), "w");
    if (!f) {
      std::fprintf(stderr, "seeml-update: cannot write --report '%s'\n",
                   report_path.c_str());
      return;
    }
    // JSON has no NaN/inf and no raw quotes: non-finite numbers become
    // null, strings are escaped.
    auto num = [&](float v) {
      if (std::isfinite(v)) std::fprintf(f, "%.8g", v);
      else std::fputs("null", f);
    };
    auto str = [&](const std::string& v) {
      std::fputc('"', f);
      for (char c : v) {
        if (c == '"' || c == '\\') std::fputc('\\', f);
        if (static_cast<unsigned char>(c) < 0x20) std::fputc(' ', f);
        else std::fputc(c, f);
      }
      std::fputc('"', f);
    };
    std::fputs("{\n  \"schema\": 1,\n  \"backend\": ", f);
    str(engine.backend_name());
    std::fputs(",\n  \"device\": ", f);
    str(engine.backend_device());
    std::fprintf(f, ",\n  \"steps\": %llu,\n  \"train_loss\": [",
                 (unsigned long long)report->steps);
    num(report->initial_avg_loss);
    std::fputs(", ", f);
    num(report->final_avg_loss);
    std::fputs("],\n", f);
    if (report->has_validation) {
      std::fputs("  \"validation_loss\": [", f);
      num(report->val_initial_loss);
      std::fputs(", ", f);
      num(report->val_final_loss);
      std::fputs("],\n", f);
    }
    if (accuracy_measured) {
      std::fputs("  \"validation_accuracy\": [", f);
      num(report->val_initial_accuracy);
      std::fputs(", ", f);
      num(report->val_final_accuracy);
      std::fputs("],\n", f);
    }
    std::fprintf(f,
                 "  \"gate\": {\"min_improvement\": %.8g, "
                 "\"require_accuracy\": %s, \"loss_ok\": %s, "
                 "\"accuracy_measured\": %s, \"accuracy_ok\": %s, "
                 "\"forced\": %s},\n  \"verdict\": \"%s\",\n"
                 "  \"committed\": %s",
                 min_improvement, require_accuracy ? "true" : "false",
                 loss_ok ? "true" : "false",
                 accuracy_measured ? "true" : "false",
                 acc_ok ? "true" : "false",
                 (!accepted && force) ? "true" : "false", verdict,
                 committed ? "true" : "false");
    if (error) {
      std::fputs(",\n  \"error\": ", f);
      str(error);
    }
    std::fputs("\n}\n", f);
    std::fclose(f);
  };
  if (!accepted && !force) {
    const char* why =
        !loss_ok ? (report->has_validation
                        ? "validation loss did not improve by the required "
                          "margin"
                        : "training loss did not improve by the required "
                          "margin")
        : !accuracy_measured
            ? "validation accuracy was not measured (the eval program has "
              "no class-label softmax over the batch)"
            : "validation accuracy dropped";
    std::fprintf(stderr,
                 "seeml-update: REJECTED — %s; source model left untouched"
                 " (--force to override)\n",
                 why);
    write_report(false, nullptr);
    return 3;
  }

  if (auto r = engine.RunMerge(); !r) {
    std::fprintf(stderr, "merge: %s\n", r.error().c_str());
    write_report(false, r.error().c_str());
    return 1;
  }
  if (auto r = engine.CommitToModel(model, out); !r) {
    std::fprintf(stderr, "commit: %s\n", r.error().c_str());
    write_report(false, r.error().c_str());
    return 1;
  }
  write_report(true, nullptr);
  std::fprintf(stderr, "seeml-update: committed '%s'\n", out.c_str());
  return 0;
}
)cpp";

// The runtime sources vendored into every emitted package. The package must
// build on a machine (or in a cross-toolchain) that has never seen this
// repository — the compiler host's checkout cannot be a build dependency of
// the deliverable.
constexpr const char* kVendoredSources[] = {
    "runtime/engine/update_engine.h",     "runtime/engine/update_engine.cc",
    "runtime/engine/contract.h",          "runtime/engine/contract.cc",
    "runtime/executor/update_kernels.h",  "runtime/executor/kernel_policy.h",
    "runtime/executor/gemm.cc",           "runtime/executor/elementwise.cc",
    "runtime/executor/activation.cc",     "runtime/executor/normalization.cc",
    "runtime/executor/loss.cc",           "runtime/executor/optimizer.cc",
    "runtime/executor/attention.cc",
    "runtime/executor/backend.h",         "runtime/executor/backend.cc",
    "runtime/executor/cpu_backend.cc",    "runtime/executor/metal_backend.h",
    "runtime/executor/metal_backend_stub.cc",
    "runtime/executor/metal_backend.mm",  "runtime/executor/metal_kernels.h",
    "runtime/feeder/dataset.h",           "runtime/feeder/dataset.cc",
    "runtime/feeder/batch_pipeline.h",    "runtime/feeder/batch_pipeline.cc",
    "runtime/validator/plan_validator.h", "runtime/validator/plan_validator.cc",
    "runtime/custodian/durable_io.h",     "runtime/custodian/durable_io.cc",
    "runtime/custodian/checkpoint.h",     "runtime/custodian/checkpoint.cc",
    "runtime/diagnostics/diagnostic.h",
    "runtime/diagnostics/feeding/error.h",
    "runtime/diagnostics/validating/error.h",
    "runtime/diagnostics/executing/error.h",
    "runtime/diagnostics/persisting/error.h",
    "source/plan/update_types.h",         "source/plan/config.h",
    "source/plan/bf16.h",
    "source/plan/instruction.h",          "source/plan/schema.h",
    "source/identity/hash.h",
    "source/parallel/parallel_for.h",     "source/parallel/parallel_for.cc",
};

std::string BuildScript() {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by seeml-update-compile: builds the self-contained\n";
  s += "# `model_update` executable from the vendored runtime sources.\n";
  s += "# Cross-compile by setting CXX to your target toolchain.\n";
  s += "set -e\n";
  s += "cd \"$(dirname \"$0\")\"\n";
  s += "CXX=\"${CXX:-c++}\"\n";
  s += "# The CPU GEMM tile geometry travels IN THE PLAN (header v11): the\n";
  s += "# compiler decided it from a measured kernel-policy table or left\n";
  s += "# the runtime's defaults. It is a throughput knob only — results\n";
  s += "# are bit-identical for any tiling the kernel accepts. This hook\n";
  s += "# changes the compiled-in default a zero header field selects:\n";
  s += "#   SEEML_TILE_FLAGS=\"-DSEEML_GEMM_TILE_K=64 -DSEEML_GEMM_TILE_N=256\"\n";
  s += "TILE_FLAGS=\"${SEEML_TILE_FLAGS-}\"\n";
  s += "# -pthread: the runtime parallelizes its kernels and pipelines the\n";
  s += "# batch feeder; SEEML_THREADS=1 at run time restores fully serial\n";
  s += "# execution (with bit-identical results — chunking is fixed).\n";
  s += "FLAGS=\"-std=c++23 -O2 -Wall -Wextra -pthread -I. $TILE_FLAGS\"\n";
  s += "# The plan reaches the binary through one of two translation units:\n";
  s += "# update_plan_embedded.S, the .incbin stub tool/pack_update.py writes\n";
  s += "# (page-aligned, assembles in seconds at any plan size; it needs only\n";
  s += "# the preprocessor and assembler, so it takes no C++ flags), or the\n";
  s += "# compiler's default decimal byte-array update_plan_embedded.cc.\n";
  s += "if [ -f update_plan_embedded.S ]; then\n";
  s += "  $CXX -c update_plan_embedded.S -o update_plan_embedded.o\n";
  s += "elif [ -f update_plan_embedded.cc ]; then\n";
  s += "  $CXX $FLAGS -c update_plan_embedded.cc -o update_plan_embedded.o\n";
  s += "else\n";
  s += "  echo \"build.sh: no embedded-plan TU here (update_plan_embedded.S"
       " or .cc);\" \\\n";
  s += "       \"run tool/pack_update.py on this directory first\" >&2\n";
  s += "  exit 1\n";
  s += "fi\n";
  s += "$CXX $FLAGS -c update_main.cc -o update_main.o\n";
  s += "$CXX $FLAGS -c source/parallel/parallel_for.cc -o parallel_for.o\n";
  s += "for unit in executor/gemm executor/elementwise executor/activation "
       "executor/normalization executor/loss executor/optimizer "
       "executor/attention executor/backend executor/cpu_backend "
       "feeder/dataset feeder/batch_pipeline validator/plan_validator "
       "custodian/durable_io custodian/checkpoint engine/contract "
       "engine/update_engine; do\n";
  s += "  $CXX $FLAGS -c \"runtime/$unit.cc\" -o \"$(basename $unit).o\"\n";
  s += "done\n";
  s += "# The Metal executor backend (--backend metal|auto) exists on Apple\n";
  s += "# hosts only: its Objective-C++ unit needs clang and the Metal +\n";
  s += "# Foundation frameworks, JIT-compiles its kernels at run time (no\n";
  s += "# Metal toolchain needed to build), and degrades to the CPU where no\n";
  s += "# device exists. Everywhere else — and under SEEML_NO_METAL=1 — the\n";
  s += "# stub takes its place and the package stays a plain C++ build, so a\n";
  s += "# Linux or Windows package is byte-for-byte what it was before.\n";
  s += "METAL_OBJ=metal_backend_stub.o\n";
  s += "METAL_LDFLAGS=\"\"\n";
  s += "# (-fobjc-arc needs a clang-family CXX; a GCC set via CXX takes the\n";
  s += "# stub, so the cross-toolchain promise holds on Darwin too.)\n";
  s += "if [ \"$(uname -s)\" = \"Darwin\" ] && [ -z \"${SEEML_NO_METAL:-}\" ] "
       "&& \"$CXX\" --version 2>/dev/null | grep -qi clang; then\n";
  s += "  $CXX $FLAGS -x objective-c++ -fobjc-arc -c "
       "runtime/executor/metal_backend.mm -o metal_backend.o\n";
  s += "  METAL_OBJ=metal_backend.o\n";
  s += "  METAL_LDFLAGS=\"-framework Metal -framework Foundation\"\n";
  s += "else\n";
  s += "  $CXX $FLAGS -c runtime/executor/metal_backend_stub.cc "
       "-o metal_backend_stub.o\n";
  s += "fi\n";
  s += "$CXX $FLAGS update_main.o update_plan_embedded.o update_engine.o "
       "contract.o dataset.o batch_pipeline.o gemm.o elementwise.o "
       "activation.o normalization.o loss.o optimizer.o attention.o "
       "backend.o cpu_backend.o $METAL_OBJ "
       "parallel_for.o durable_io.o plan_validator.o checkpoint.o "
       "$METAL_LDFLAGS -o model_update\n";
  s += "# The .o files are intermediates; the deliverable is the binary.\n";
  s += "rm -f ./*.o\n";
  s += "echo \"built: $(pwd)/model_update\"\n";
  return s;
}

}  // namespace

std::expected<EmitPaths, std::string> EmitNativePackage(
    const std::vector<uint8_t>& plan, const std::string& out_dir,
    const std::string& repo_root, const EmitOptions& options) {
  std::error_code ec;
  std::filesystem::create_directories(out_dir, ec);
  if (ec)
    return generating::FileError(generating::kNativeEmitter,
                                 "cannot create", out_dir);

  EmitPaths paths{
      .plan_file = out_dir + "/update_plan.seeu",
      .embedded_tu =
          options.embed_plan_tu ? out_dir + "/update_plan_embedded.cc" : "",
      .main_tu = out_dir + "/update_main.cc",
      .build_script = out_dir + "/build.sh",
  };

  {
    std::ofstream f(paths.plan_file, std::ios::binary | std::ios::trunc);
    if (!f)
      return generating::Error(generating::kNativeEmitter,
                               "cannot write plan file");
    f.write(reinterpret_cast<const char*>(plan.data()),
            static_cast<std::streamsize>(plan.size()));
    f.close();
    if (f.fail())
      return generating::FileError(generating::kNativeEmitter,
                                   "short write to", paths.plan_file);
  }
  // A package carries exactly one embedded-plan TU, so build.sh's choice is
  // never ambiguous: whichever of the pair this emission does not write is
  // removed, in case an earlier emission into the same directory (or the
  // packer) left it behind. Otherwise a stale .incbin stub from a previous
  // pack would silently win over the fresh decimal TU, or a stale decimal
  // TU would ship beside the stub the packer is about to add.
  if (options.embed_plan_tu) {
    if (auto r = WriteEmbeddedTU(paths.embedded_tu, plan); !r)
      return std::unexpected(r.error());
    std::filesystem::remove(out_dir + "/update_plan_embedded.S", ec);
  } else {
    std::filesystem::remove(out_dir + "/update_plan_embedded.cc", ec);
  }
  if (auto r = WriteFile(paths.main_tu, kMainTU); !r)
    return std::unexpected(r.error());

  // Vendor the runtime into the package so it builds without the repo.
  for (const char* rel : kVendoredSources) {
    const auto src = std::filesystem::path(repo_root) / rel;
    const auto dst = std::filesystem::path(out_dir) / rel;
    std::filesystem::create_directories(dst.parent_path(), ec);
    if (ec)
      return generating::FileError(generating::kNativeEmitter,
                                   "cannot create",
                                   dst.parent_path().string());
    std::filesystem::copy_file(
        src, dst, std::filesystem::copy_options::overwrite_existing, ec);
    if (ec)
      return generating::Error(generating::kNativeEmitter,
                               "cannot vendor '" + src.string() + "' (" +
                                   ec.message() + ")");
  }

  // The GEMM tile geometry is a plan property now (header v11, decided by
  // the driver from the kernel-policy table or the defaults), so the build
  // script bakes nothing host-derived: the analytic tiling it used to emit
  // ran 1.3–3.3x slower than the kernel defaults (#90).
  if (auto r = WriteFile(paths.build_script, BuildScript(),
                         /*executable=*/true);
      !r)
    return std::unexpected(r.error());

  return paths;
}

}  // namespace seeml::update
