#include "compiler/backend/trainer/native_emitter.h"

#include <filesystem>
#include <fstream>

#include "compiler/backend/architecture/host_arch.h"
#include "compiler/diagnostics/generating/error.h"
#include "source/parallel/parallel_for.h"

namespace seeml::update {

namespace generating = seeml::diag::generating;

namespace {

std::expected<void, std::string> WriteFile(const std::string& path,
                                           const std::string& content,
                                           bool executable = false) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f)
    return generating::FileError(generating::kNativeEmitter, "cannot write",
                                 path);
  f << content;
  // Close before the state check: with contents this small the whole file
  // can sit in the stream buffer, so a failed flush-at-close is the only
  // signal a truncated package would ever give.
  f.close();
  if (f.fail())
    return generating::FileError(generating::kNativeEmitter, "short write to",
                                 path);
  if (executable) {
    std::error_code ec;
    std::filesystem::permissions(path,
                                 std::filesystem::perms::owner_all |
                                     std::filesystem::perms::group_read |
                                     std::filesystem::perms::group_exec |
                                     std::filesystem::perms::others_read |
                                     std::filesystem::perms::others_exec,
                                 ec);
  }
  return {};
}

std::string EmbedPlanAsTU(const std::vector<uint8_t>& plan) {
  std::string tu;
  tu.reserve(plan.size() * 5 + 512);
  tu +=
      "// Generated by seeml-update-compile. The compiled Update Plan as an\n"
      "// object-file byte array: instruction streams, memory layout, frozen\n"
      "// weights, and adapter initialization — the entire update, as data.\n"
      "#include <cstddef>\n\n"
      "extern const unsigned char kSeemlUpdatePlan[] "
      "__attribute__((aligned(64)));\n"
      "extern const size_t kSeemlUpdatePlanSize;\n\n"
      "const unsigned char kSeemlUpdatePlan[] __attribute__((aligned(64))) = "
      "{\n";
  // Manual decimal emission: a snprintf call per byte dominates emission
  // time once plans reach megabytes (frozen weights live in the blob).
  // Three digit appends and a comma beat the formatter by an order of
  // magnitude and need no format-string parsing. Each byte's text (and its
  // line break, keyed off the global index) is independent of every other
  // byte, so fixed chunks render in parallel and concatenate in order —
  // the output is character-identical to the serial emitter.
  constexpr size_t kEmbedGrain = 256 * 1024;
  std::vector<std::string> parts(
      ParallelChunkCount(plan.size(), kEmbedGrain));
  ParallelFor(plan.size(), kEmbedGrain,
              [&](size_t begin, size_t end, size_t chunk) {
                std::string& out = parts[chunk];
                out.reserve((end - begin) * 4 + 8);
                for (size_t i = begin; i < end; ++i) {
                  const unsigned v = plan[i];
                  if (v >= 100) {
                    out += static_cast<char>('0' + v / 100);
                    out += static_cast<char>('0' + (v / 10) % 10);
                    out += static_cast<char>('0' + v % 10);
                  } else if (v >= 10) {
                    out += static_cast<char>('0' + v / 10);
                    out += static_cast<char>('0' + v % 10);
                  } else {
                    out += static_cast<char>('0' + v);
                  }
                  out += ',';
                  if ((i + 1) % 24 == 0) out += '\n';
                }
              });
  for (const std::string& part : parts) tu += part;
  tu += "\n};\nconst size_t kSeemlUpdatePlanSize = sizeof(kSeemlUpdatePlan);\n";
  return tu;
}

constexpr const char* kMainTU = R"cpp(// Generated by seeml-update-compile.
// The on-device model update program: train LoRA adapters against local
// data, gate on held-out validation, merge deltas, commit durably.
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>

#include "runtime/engine/update_engine.h"
#include "runtime/feeder/dataset.h"

extern const unsigned char kSeemlUpdatePlan[];
extern const size_t kSeemlUpdatePlanSize;

namespace {

const char* Arg(int argc, char** argv, const char* flag, const char* dflt) {
  for (int i = 1; i + 1 < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return argv[i + 1];
  return dflt;
}

bool Has(int argc, char** argv, const char* flag) {
  for (int i = 1; i < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return true;
  return false;
}

bool ParseU64(const char* s, uint64_t* out) {
  errno = 0;
  char* end = nullptr;
  const unsigned long long v = std::strtoull(s, &end, 10);
  if (errno != 0 || end == s || *end != '\0' || *s == '-') return false;
  *out = v;
  return true;
}

bool ParseF64(const char* s, double* out) {
  errno = 0;
  char* end = nullptr;
  const double v = std::strtod(s, &end);
  if (errno != 0 || end == s || *end != '\0') return false;
  *out = v;
  return true;
}

constexpr const char* kUsage =
    "usage: model_update --model <source.smf> --data <corpus.sds>"
    " [--out updated.smf] [--steps N] [--seed S]"
    " [--val-frac F] [--checkpoint ckpt] [--checkpoint-every N]"
    " [--resume] [--loss-log curve.csv] [--force] [--help]\n";

/// Every argv slot must be a known flag or a known flag's value: the
/// compiler CLI treats unconsumed arguments as hard errors, and the device
/// runner follows the same rule — a typo'd --val-frc must not silently
/// train with the default.
bool ArgsOk(int argc, char** argv) {
  static const char* const kValueFlags[] = {
      "--model",      "--data",     "--out",
      "--steps",      "--seed",     "--val-frac",
      "--checkpoint", "--loss-log", "--checkpoint-every"};
  static const char* const kBoolFlags[] = {"--force", "--resume", "--help",
                                           "-h"};
  for (int i = 1; i < argc; ++i) {
    // Empty argv slots are shell debris (a quoted-but-unset "$VAR"), not
    // typos: nothing can be misread from one, and the pre-strict runner
    // accepted them — rejecting them would break existing wrappers for
    // zero safety gain. They stay ignorable.
    if (argv[i][0] == '\0') continue;
    bool known = false;
    for (const char* f : kValueFlags) {
      if (std::strcmp(argv[i], f) != 0) continue;
      // A '-'-prefixed value is a flag that swallowed its neighbor
      // (`--out --force`), not a value: Arg() would take it as a filename
      // while Has() independently still sees it as set. No legitimate
      // value here starts with '-' (paths aside, and steps/seed/val-frac
      // reject negatives anyway), so refuse rather than double-read.
      if (i + 1 >= argc || argv[i + 1][0] == '-') {
        std::fprintf(stderr, "model_update: %s requires a value\n", argv[i]);
        return false;
      }
      known = true;
      ++i;
      break;
    }
    if (!known)
      for (const char* f : kBoolFlags)
        if (std::strcmp(argv[i], f) == 0) {
          known = true;
          break;
        }
    if (!known) {
      std::fprintf(stderr,
                   "model_update: unknown argument '%s' (see --help)\n",
                   argv[i]);
      return false;
    }
  }
  return true;
}

}  // namespace

int main(int argc, char** argv) {
  // Strictness before convenience: ArgsOk first, so `--out -h` is a
  // missing-value error rather than a help hit on a swallowed slot. After
  // it passes, every argv slot is a known flag or a non-flag value, and
  // Has()/Arg() below cannot double-read a slot.
  if (!ArgsOk(argc, argv)) return 2;
  if (Has(argc, argv, "--help") || Has(argc, argv, "-h")) {
    std::fputs(kUsage, stdout);
    return 0;
  }

  const std::string model = Arg(argc, argv, "--model", "");
  const std::string data = Arg(argc, argv, "--data", "");
  const std::string out = Arg(argc, argv, "--out", "updated_model.smf");
  const std::string loss_log = Arg(argc, argv, "--loss-log", "");
  const bool force = Has(argc, argv, "--force");

  uint64_t steps = 0, seed = 0;
  double val_frac = 0.1;
  // The negated in-range form rejects NaN, which `< 0.0 || >= 1.0` lets
  // through — and a NaN val_frac silently disables the validation gate.
  if (!ParseU64(Arg(argc, argv, "--steps", "0"), &steps) ||
      !ParseU64(Arg(argc, argv, "--seed", "0"), &seed) ||
      !ParseF64(Arg(argc, argv, "--val-frac", "0.1"), &val_frac) ||
      !(val_frac >= 0.0 && val_frac < 1.0)) {
    std::fprintf(stderr, "invalid numeric argument\n");
    return 2;
  }

  if (model.empty() || data.empty()) {
    std::fputs(kUsage, stderr);
    return 2;
  }

  seeml::update_rt::UpdateEngine engine;
  if (auto r = engine.LoadFromMemory(kSeemlUpdatePlan, kSeemlUpdatePlanSize); !r) {
    std::fprintf(stderr, "load: %s\n", r.error().c_str());
    return 1;
  }

  // Fail fast: the plan's emit offsets are only meaningful inside the exact
  // file it was compiled from, and commit would refuse anyway — but only
  // after the full training run. One file scan here buys that refusal now.
  if (auto r = engine.VerifySourceModel(model); !r) {
    std::fprintf(stderr, "model: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr,
               "seeml-update: resource contract — arena %llu bytes"
               " (%llu persistent)\n",
               (unsigned long long)engine.header().arena_size,
               (unsigned long long)engine.header().persistent_size);

  auto dataset = seeml::update_rt::Dataset::LoadFromFile(data);
  if (!dataset) {
    std::fprintf(stderr, "data: %s\n", dataset.error().c_str());
    return 1;
  }

  // Held-out validation split (before shuffling) drives the regression
  // gate; --val-frac 0 falls back to the training-loss trend.
  std::optional<seeml::update_rt::Dataset> val_set;
  if (val_frac > 0.0) {
    auto split = dataset->SplitValidation(val_frac);
    if (!split) {
      std::fprintf(stderr, "data: %s\n", split.error().c_str());
      return 1;
    }
    val_set = std::move(*split);
  }
  dataset->EnableShuffle(seed);

  seeml::update_rt::TrainOptions options;
  options.checkpoint_path = Arg(argc, argv, "--checkpoint", "");
  options.resume = Has(argc, argv, "--resume");
  options.validation = val_set ? &*val_set : nullptr;
  options.record_loss_curve = !loss_log.empty();
  if (!ParseU64(Arg(argc, argv, "--checkpoint-every", "0"),
                &options.checkpoint_every)) {
    std::fprintf(stderr, "invalid --checkpoint-every\n");
    return 2;
  }

  auto report = engine.Train(*dataset, steps, options);
  if (!report) {
    std::fprintf(stderr, "train: %s\n", report.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: train loss %.6f -> %.6f over %llu steps\n",
               report->initial_avg_loss, report->final_avg_loss,
               (unsigned long long)report->steps);
  if (report->has_validation)
    std::fprintf(stderr, "seeml-update: validation loss %.6f -> %.6f\n",
                 report->val_initial_loss, report->val_final_loss);
  if (report->has_val_accuracy)
    std::fprintf(stderr, "seeml-update: validation accuracy %.4f -> %.4f\n",
                 report->val_initial_accuracy, report->val_final_accuracy);

  if (!loss_log.empty()) {
    std::FILE* f = std::fopen(loss_log.c_str(), "w");
    if (f) {
      std::fprintf(f, "step,loss\n");
      for (size_t i = 0; i < report->loss_curve.size(); ++i)
        std::fprintf(f, "%zu,%.6f\n", i + 1, report->loss_curve[i]);
      std::fclose(f);
    }
  }

  // Regression gate: a failed update must leave the device untouched.
  // With a validation split this gates on held-out loss, not training loss.
  if (!report->improved() && !force) {
    std::fprintf(stderr,
                 "seeml-update: REJECTED — %s loss did not improve; source"
                 " model left untouched (--force to override)\n",
                 report->has_validation ? "validation" : "training");
    return 3;
  }

  if (auto r = engine.RunMerge(); !r) {
    std::fprintf(stderr, "merge: %s\n", r.error().c_str());
    return 1;
  }
  if (auto r = engine.CommitToModel(model, out); !r) {
    std::fprintf(stderr, "commit: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: committed '%s'\n", out.c_str());
  return 0;
}
)cpp";

// The runtime sources vendored into every emitted package. The package must
// build on a machine (or in a cross-toolchain) that has never seen this
// repository — the compiler host's checkout cannot be a build dependency of
// the deliverable.
constexpr const char* kVendoredSources[] = {
    "runtime/engine/update_engine.h",     "runtime/engine/update_engine.cc",
    "runtime/engine/contract.h",          "runtime/engine/contract.cc",
    "runtime/executor/update_kernels.h",  "runtime/executor/kernel_policy.h",
    "runtime/executor/gemm.cc",           "runtime/executor/elementwise.cc",
    "runtime/executor/activation.cc",     "runtime/executor/normalization.cc",
    "runtime/executor/loss.cc",           "runtime/executor/optimizer.cc",
    "runtime/executor/attention.cc",
    "runtime/feeder/dataset.h",           "runtime/feeder/dataset.cc",
    "runtime/feeder/batch_pipeline.h",    "runtime/feeder/batch_pipeline.cc",
    "runtime/validator/plan_validator.h", "runtime/validator/plan_validator.cc",
    "runtime/custodian/durable_io.h",     "runtime/custodian/durable_io.cc",
    "runtime/custodian/checkpoint.h",     "runtime/custodian/checkpoint.cc",
    "runtime/diagnostics/diagnostic.h",
    "runtime/diagnostics/feeding/error.h",
    "runtime/diagnostics/validating/error.h",
    "runtime/diagnostics/executing/error.h",
    "runtime/diagnostics/persisting/error.h",
    "source/plan/update_types.h",         "source/plan/config.h",
    "source/plan/instruction.h",          "source/plan/schema.h",
    "source/identity/hash.h",
    "source/parallel/parallel_for.h",     "source/parallel/parallel_for.cc",
};

std::string BuildScript(const GemmTiling* tiling) {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by seeml-update-compile: builds the self-contained\n";
  s += "# `model_update` executable from the vendored runtime sources.\n";
  s += "# Cross-compile by setting CXX to your target toolchain.\n";
  s += "set -e\n";
  s += "cd \"$(dirname \"$0\")\"\n";
  s += "CXX=\"${CXX:-c++}\"\n";
  if (tiling) {
    s += "# GEMM tile geometry derived by the compiler's architecture\n";
    s += "# analysis from THIS compile host's cache hierarchy (kc x nc\n";
    s += "# panel of B within half of L1). It is a throughput knob only —\n";
    s += "# results are bit-identical for any tiling the kernel accepts.\n";
    s += "# Cross-compiling for a device with different caches? Override\n";
    s += "# it, or clear it to the kernel's portable defaults:\n";
    s += "#   SEEML_TILE_FLAGS=\"\" sh build.sh\n";
    s += "TILE_FLAGS=\"${SEEML_TILE_FLAGS--DSEEML_GEMM_TILE_K=" +
         std::to_string(tiling->kc) +
         " -DSEEML_GEMM_TILE_N=" + std::to_string(tiling->nc) + "}\"\n";
  } else {
    s += "TILE_FLAGS=\"${SEEML_TILE_FLAGS-}\"\n";
  }
  s += "# -pthread: the runtime parallelizes its kernels and pipelines the\n";
  s += "# batch feeder; SEEML_THREADS=1 at run time restores fully serial\n";
  s += "# execution (with bit-identical results — chunking is fixed).\n";
  s += "FLAGS=\"-std=c++23 -O2 -Wall -Wextra -pthread -I. $TILE_FLAGS\"\n";
  s += "$CXX $FLAGS -c update_plan_embedded.cc -o update_plan_embedded.o\n";
  s += "$CXX $FLAGS -c update_main.cc -o update_main.o\n";
  s += "$CXX $FLAGS -c source/parallel/parallel_for.cc -o parallel_for.o\n";
  s += "for unit in executor/gemm executor/elementwise executor/activation "
       "executor/normalization executor/loss executor/optimizer "
       "executor/attention "
       "feeder/dataset feeder/batch_pipeline validator/plan_validator "
       "custodian/durable_io custodian/checkpoint engine/contract "
       "engine/update_engine; do\n";
  s += "  $CXX $FLAGS -c \"runtime/$unit.cc\" -o \"$(basename $unit).o\"\n";
  s += "done\n";
  s += "$CXX $FLAGS update_main.o update_plan_embedded.o update_engine.o "
       "contract.o dataset.o batch_pipeline.o gemm.o elementwise.o "
       "activation.o normalization.o loss.o optimizer.o attention.o "
       "parallel_for.o durable_io.o plan_validator.o checkpoint.o "
       "-o model_update\n";
  s += "# The .o files are intermediates; the deliverable is the binary.\n";
  s += "rm -f ./*.o\n";
  s += "echo \"built: $(pwd)/model_update\"\n";
  return s;
}

}  // namespace

std::expected<EmitPaths, std::string> EmitNativePackage(
    const std::vector<uint8_t>& plan, const std::string& out_dir,
    const std::string& repo_root) {
  std::error_code ec;
  std::filesystem::create_directories(out_dir, ec);
  if (ec)
    return generating::FileError(generating::kNativeEmitter,
                                 "cannot create", out_dir);

  EmitPaths paths{
      .plan_file = out_dir + "/update_plan.seeu",
      .embedded_tu = out_dir + "/update_plan_embedded.cc",
      .main_tu = out_dir + "/update_main.cc",
      .build_script = out_dir + "/build.sh",
  };

  {
    std::ofstream f(paths.plan_file, std::ios::binary | std::ios::trunc);
    if (!f)
      return generating::Error(generating::kNativeEmitter,
                               "cannot write plan file");
    f.write(reinterpret_cast<const char*>(plan.data()),
            static_cast<std::streamsize>(plan.size()));
    f.close();
    if (f.fail())
      return generating::FileError(generating::kNativeEmitter,
                                   "short write to", paths.plan_file);
  }
  if (auto r = WriteFile(paths.embedded_tu, EmbedPlanAsTU(plan)); !r)
    return std::unexpected(r.error());
  if (auto r = WriteFile(paths.main_tu, kMainTU); !r)
    return std::unexpected(r.error());

  // Vendor the runtime into the package so it builds without the repo.
  for (const char* rel : kVendoredSources) {
    const auto src = std::filesystem::path(repo_root) / rel;
    const auto dst = std::filesystem::path(out_dir) / rel;
    std::filesystem::create_directories(dst.parent_path(), ec);
    if (ec)
      return generating::FileError(generating::kNativeEmitter,
                                   "cannot create",
                                   dst.parent_path().string());
    std::filesystem::copy_file(
        src, dst, std::filesystem::copy_options::overwrite_existing, ec);
    if (ec)
      return generating::Error(generating::kNativeEmitter,
                               "cannot vendor '" + src.string() + "' (" +
                                   ec.message() + ")");
  }

  // Wire the architecture analysis into the delivered program: the tiling
  // suggested for this host becomes the package's default GEMM geometry.
  // Two-tier discipline: the suggestion is gated through its own contract,
  // and a violation falls back to the kernel's portable defaults instead of
  // failing the emission — a bad hint may cost throughput, never the build.
  const HostArchInfo arch = DetectHostArch();
  GemmTiling tiling = SuggestGemmTiling(arch);
  const GemmTiling* tiling_for_script = &tiling;
  if (auto ok = ValidateGemmTiling(tiling, arch); !ok) {
    seeml::diag::Fallback(generating::kNativeEmitter,
                          "suggested GEMM tiling failed its contract (" +
                              ok.error() +
                              ") — falling back to portable default tiles");
    tiling_for_script = nullptr;
  }

  if (auto r = WriteFile(paths.build_script, BuildScript(tiling_for_script),
                         /*executable=*/true);
      !r)
    return std::unexpected(r.error());

  return paths;
}

}  // namespace seeml::update
