#ifndef SEEML_TEST_SUPPORT_BUILDERS_H_
#define SEEML_TEST_SUPPORT_BUILDERS_H_

#include <cstdint>
#include <expected>
#include <string>
#include <vector>

#include "source/plan/update_types.h"
#include "runtime/feeder/dataset.h"
#include "runtime/engine/update_engine.h"
#include "source/language/model_format.h"

// =============================================================================
// Shared fixtures for the SeeML test suites — the support façade. The
// implementations are partitioned per discipline, in the fashion of the
// compiler and runtime subsystems:
//   models.cc   deterministic SMF model builders + the default UpdateConfig
//   corpora.cc  synthetic datasets (classification / regression / unlabeled)
//   probes.cc   engine-arena introspection + the test-run environment
// Everything is seeded — two calls with the same arguments produce identical
// bytes, which the determinism tests rely on.
// =============================================================================

namespace seeml::testing {

/// Reinterprets a float vector as its raw little-endian bytes (SMF blobs).
std::vector<uint8_t> AsBytes(const std::vector<float>& v);

/// `n` samples from N(0, std), deterministic in `seed`.
std::vector<float> RandnVector(size_t n, uint64_t seed, float stddev = 1.0f);

/// A deterministic 2-layer MLP:  in -> hidden (relu) -> out.
/// Tensors: x (dynamic batch), w1, b1, w2, b2; ops: mm1, ab1, relu1, mm2, ab2.
update::SmfModel MakeMlp(int64_t in_dim, int64_t hidden, int64_t out_dim,
                         uint64_t seed);

/// MakeMlp generalized to `layers` hidden Linear+ReLU layers of `hidden`
/// width — the benchmark harness's feature-plan shapes:
///   in -> [hidden (relu)] x layers -> out
/// Layer i's tensors/ops carry the suffix i+1 (w1/b1/mm1/ab1/relu1, ...).
update::SmfModel MakeMlpStack(int64_t in_dim, int64_t hidden, int64_t layers,
                              int64_t out_dim, uint64_t seed);

/// A two-layer net whose MatMuls share one square weight tensor "w"
/// (weight tying):  x[?,dim] @ w -> relu -> @ w -> y.
update::SmfModel MakeTiedMlp(int64_t dim, uint64_t seed);

/// A gated block exercising every v2 operator (and, unlike ReLU nets, one
/// that propagates non-finite values honestly into the loss):
///   h1 = gelu(x@w1 + b1); h2 = silu(x@w2 + b2); g = h1 * h2
///   n = layer_norm(g, gamma, beta); logits = n@w3 + b3
update::SmfModel MakeGatedNet(int64_t in_dim, int64_t hidden, int64_t out_dim,
                              uint64_t seed);

/// A one-block pre-norm causal decoder exercising every v3 operator
/// (RmsNorm / Rope / Attention / Add plus the SwiGLU MLP), with a
/// vocab-logit head. Rows are pre-embedded positions grouped into
/// sequences of `seq` (m.seq_len = seq); requires heads | dim and an even
/// head width:
///   n1 = rms_norm(x, g1); q/k/v = n1@wq/wk/wv; a = attn(rope(q), rope(k), v)
///   x1 = x + a@wo; n2 = rms_norm(x1, g2)
///   x2 = x1 + (silu(n2@wg) * (n2@wu))@wd; logits = rms_norm(x2, gf)@wh
update::SmfModel MakeTinyDecoder(int64_t dim, int64_t heads, int64_t seq,
                                 int64_t ffn, int64_t vocab, uint64_t seed);

/// MakeTinyDecoder generalized to `blocks` stacked pre-norm blocks (one
/// shared final-norm + vocab head) — the benchmark harness's decoder
/// shapes. Block i's tensors/ops carry the prefix "l<i>.".
update::SmfModel MakeDecoderStack(int64_t dim, int64_t heads, int64_t seq,
                                  int64_t ffn, int64_t vocab, int64_t blocks,
                                  uint64_t seed);

/// A one-block token-native decoder (SMF v4): rank-1 dynamic i32 input →
/// Embedding[vocab, dim] → the pre-norm attention/SwiGLU block of
/// MakeTinyDecoder → logits over `vocab`. m.seq_len = seq.
update::SmfModel MakeTinyTokenDecoder(int64_t vocab, int64_t dim,
                                      int64_t heads, int64_t seq,
                                      int64_t ffn, uint64_t seed);

/// The repository checkout the test binaries were configured from (the
/// emitter suite vendors runtime sources out of it).
std::string RepoRoot();

/// A linearly separable 2-class problem: label = 1[x . w_true > 0].
std::expected<update_rt::Dataset, std::string> MakeClassificationData(
    uint64_t n, int64_t in_dim, uint64_t seed);

/// A linear regression problem with dense f32 targets: y = x @ W_true.
std::expected<update_rt::Dataset, std::string> MakeRegressionData(
    uint64_t n, int64_t in_dim, int64_t out_dim, uint64_t seed);

/// Unlabeled inputs (distillation corpora).
std::expected<update_rt::Dataset, std::string> MakeUnlabeledData(
    uint64_t n, int64_t in_dim, uint64_t seed);

/// A learnable token corpus (SDS v2): `records` sequences of (seq + 1)
/// ids over [0, vocab), generated by the deterministic successor rule
/// t' = (3t + 1) mod vocab from a seeded random start — the next token is
/// a function of the current one, so next-token loss can approach zero.
std::expected<update_rt::Dataset, std::string> MakeTokenCorpus(
    uint64_t records, uint64_t seq, int64_t vocab, uint64_t seed);

/// The suites' default update configuration: softmax cross-entropy, LoRA
/// rank 4 / alpha 8 / seed 7.
update::UpdateConfig BaseConfig(int64_t batch);

// --- UpdateEngine arena helpers -----------------------------------------------

float ReadArenaF32(update_rt::UpdateEngine& e, uint64_t ref,
                   uint64_t index = 0);
void WriteArenaF32(update_rt::UpdateEngine& e, uint64_t ref, uint64_t index,
                   float v);

/// Copies a batch directly into the plan's I/O slots (bypassing Dataset).
/// Sizes must match the plan header exactly; aborts otherwise.
void FillSlots(update_rt::UpdateEngine& e, const std::vector<float>& x,
               const std::vector<int32_t>& labels);

/// Token-plan variant of FillSlots: stages i32 token ids and their
/// next-token class labels.
void FillTokenSlots(update_rt::UpdateEngine& e,
                    const std::vector<int32_t>& tokens,
                    const std::vector<int32_t>& labels);

}  // namespace seeml::testing

#endif  // SEEML_TEST_SUPPORT_BUILDERS_H_
