#include "source/update/native_emitter.h"

#include <filesystem>
#include <fstream>

namespace seeml::update {

namespace {

std::expected<void, std::string> WriteFile(const std::string& path,
                                           const std::string& content,
                                           bool executable = false) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f) return std::unexpected("NativeEmitter: cannot write '" + path + "'");
  f << content;
  if (!f) return std::unexpected("NativeEmitter: short write to '" + path + "'");
  f.close();
  if (executable) {
    std::error_code ec;
    std::filesystem::permissions(path,
                                 std::filesystem::perms::owner_all |
                                     std::filesystem::perms::group_read |
                                     std::filesystem::perms::group_exec |
                                     std::filesystem::perms::others_read |
                                     std::filesystem::perms::others_exec,
                                 ec);
  }
  return {};
}

std::string EmbedPlanAsTU(const std::vector<uint8_t>& plan) {
  std::string tu;
  tu.reserve(plan.size() * 5 + 512);
  tu +=
      "// Generated by seeml-update-compile. The compiled Update Plan as an\n"
      "// object-file byte array: instruction streams, memory layout, frozen\n"
      "// weights, and adapter initialization — the entire update, as data.\n"
      "#include <cstddef>\n\n"
      "extern const unsigned char kSeemlUpdatePlan[] "
      "__attribute__((aligned(64)));\n"
      "extern const size_t kSeemlUpdatePlanSize;\n\n"
      "const unsigned char kSeemlUpdatePlan[] __attribute__((aligned(64))) = "
      "{\n";
  char buf[8];
  for (size_t i = 0; i < plan.size(); ++i) {
    std::snprintf(buf, sizeof(buf), "%u,", plan[i]);
    tu += buf;
    if ((i + 1) % 24 == 0) tu += '\n';
  }
  tu += "\n};\nconst size_t kSeemlUpdatePlanSize = sizeof(kSeemlUpdatePlan);\n";
  return tu;
}

constexpr const char* kMainTU = R"cpp(// Generated by seeml-update-compile.
// The on-device model update program: train LoRA adapters against local
// data, gate on regression, merge via linear algebra, commit atomically.
#include <cstdio>
#include <cstring>
#include <string>

#include "source/update_runtime/dataset.h"
#include "source/update_runtime/update_engine.h"

extern const unsigned char kSeemlUpdatePlan[];
extern const size_t kSeemlUpdatePlanSize;

namespace {

const char* Arg(int argc, char** argv, const char* flag, const char* dflt) {
  for (int i = 1; i + 1 < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return argv[i + 1];
  return dflt;
}

bool Has(int argc, char** argv, const char* flag) {
  for (int i = 1; i < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return true;
  return false;
}

}  // namespace

int main(int argc, char** argv) {
  const std::string model = Arg(argc, argv, "--model", "");
  const std::string data = Arg(argc, argv, "--data", "");
  const std::string out = Arg(argc, argv, "--out", "updated_model.smf");
  const uint64_t steps = std::strtoull(Arg(argc, argv, "--steps", "0"), nullptr, 10);
  const bool force = Has(argc, argv, "--force");

  if (model.empty() || data.empty()) {
    std::fprintf(stderr,
                 "usage: model_update --model <source.smf> --data <corpus.sds>"
                 " [--out updated.smf] [--steps N] [--checkpoint ckpt]"
                 " [--checkpoint-every N] [--resume] [--force]\n");
    return 2;
  }

  seeml::update_rt::UpdateEngine engine;
  if (auto r = engine.LoadFromMemory(kSeemlUpdatePlan, kSeemlUpdatePlanSize); !r) {
    std::fprintf(stderr, "load: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr,
               "seeml-update: resource contract — arena %llu bytes"
               " (%llu persistent)\n",
               (unsigned long long)engine.header().arena_size,
               (unsigned long long)engine.header().persistent_size);

  auto dataset = seeml::update_rt::Dataset::LoadFromFile(data);
  if (!dataset) {
    std::fprintf(stderr, "data: %s\n", dataset.error().c_str());
    return 1;
  }

  seeml::update_rt::TrainOptions options;
  options.checkpoint_path = Arg(argc, argv, "--checkpoint", "");
  options.checkpoint_every =
      std::strtoull(Arg(argc, argv, "--checkpoint-every", "0"), nullptr, 10);
  options.resume = Has(argc, argv, "--resume");

  auto report = engine.Train(*dataset, steps, options);
  if (!report) {
    std::fprintf(stderr, "train: %s\n", report.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: loss %.6f -> %.6f over %llu steps\n",
               report->initial_avg_loss, report->final_avg_loss,
               (unsigned long long)report->steps);

  // Regression gate: a failed update must leave the device untouched.
  if (!report->improved() && !force) {
    std::fprintf(stderr,
                 "seeml-update: REJECTED — loss did not improve; source model"
                 " left untouched (--force to override)\n");
    return 3;
  }

  if (auto r = engine.RunMerge(); !r) {
    std::fprintf(stderr, "merge: %s\n", r.error().c_str());
    return 1;
  }
  if (auto r = engine.CommitToModel(model, out); !r) {
    std::fprintf(stderr, "commit: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: committed '%s'\n", out.c_str());
  return 0;
}
)cpp";

std::string BuildScript(const std::string& repo_root) {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by seeml-update-compile: builds the deliverable object\n";
  s += "# files and links the self-contained `model_update` executable.\n";
  s += "set -e\n";
  s += "cd \"$(dirname \"$0\")\"\n";
  s += "REPO=\"" + repo_root + "\"\n";
  s += "CXX=\"${CXX:-c++}\"\n";
  s += "FLAGS=\"-std=c++23 -O2 -Wall -Wextra -I$REPO\"\n";
  s += "$CXX $FLAGS -c update_plan_embedded.cc -o update_plan_embedded.o\n";
  s += "$CXX $FLAGS -c update_main.cc -o update_main.o\n";
  s += "$CXX $FLAGS -c \"$REPO/source/update_runtime/update_kernels.cc\" -o "
       "update_kernels.o\n";
  s += "$CXX $FLAGS -c \"$REPO/source/update_runtime/dataset.cc\" -o "
       "dataset.o\n";
  s += "$CXX $FLAGS -c \"$REPO/source/update_runtime/update_engine.cc\" -o "
       "update_engine.o\n";
  s += "$CXX update_main.o update_plan_embedded.o update_engine.o dataset.o "
       "update_kernels.o -o model_update\n";
  s += "echo \"built: $(pwd)/model_update\"\n";
  return s;
}

}  // namespace

std::expected<EmitPaths, std::string> EmitNativePackage(
    const std::vector<uint8_t>& plan, const std::string& out_dir,
    const std::string& repo_root) {
  std::error_code ec;
  std::filesystem::create_directories(out_dir, ec);
  if (ec)
    return std::unexpected("NativeEmitter: cannot create '" + out_dir + "'");

  EmitPaths paths{
      .plan_file = out_dir + "/update_plan.seeu",
      .embedded_tu = out_dir + "/update_plan_embedded.cc",
      .main_tu = out_dir + "/update_main.cc",
      .build_script = out_dir + "/build.sh",
  };

  {
    std::ofstream f(paths.plan_file, std::ios::binary | std::ios::trunc);
    if (!f)
      return std::unexpected("NativeEmitter: cannot write plan file");
    f.write(reinterpret_cast<const char*>(plan.data()),
            static_cast<std::streamsize>(plan.size()));
  }
  if (auto r = WriteFile(paths.embedded_tu, EmbedPlanAsTU(plan)); !r)
    return std::unexpected(r.error());
  if (auto r = WriteFile(paths.main_tu, kMainTU); !r)
    return std::unexpected(r.error());
  if (auto r = WriteFile(paths.build_script,
                         BuildScript(std::filesystem::absolute(repo_root)
                                         .lexically_normal()
                                         .string()),
                         /*executable=*/true);
      !r)
    return std::unexpected(r.error());

  return paths;
}

}  // namespace seeml::update
