#!/usr/bin/env python3
"""pack_update.py — the SeeML package assembler (Two-Plane Overhaul, P1).

Embeds a compiled update plan into an emitted package as an `.incbin`
assembly stub — `update_plan_embedded.S` — in place of the compiler's decimal
byte-array C++ translation unit, and optionally drives the package's own
`build.sh`.

    seeml-update-compile --source m.smf --out pkg/ ... --no-embed
    python3 tool/pack_update.py pkg/ --build

Why this exists: the decimal TU renders every plan byte as ~3.9 characters
of C++ that the host compiler must then parse at -O2 — 16.5 minutes and a
948 MB translation unit at 135M parameters. The stub below is a few hundred
bytes of assembly that tells the assembler to splice the `.seeu` file in
verbatim: the host compiler never parses weight bytes again, the plan lands
on disk exactly once, and embedding takes well under a second at any size.

The emitted package is unchanged in kind: still dependency-free C++ that
builds anywhere the generated build.sh already ran — the stub needs only
the preprocessor and assembler every GCC- or Clang-compatible driver
carries (`c++ -c update_plan_embedded.S`), on ELF, Mach-O and MinGW alike.
Python runs on the build host only; nothing here ships to the device.

Dependency tier 0: standard library only. Strict CLI, like every SeeML tool:
an unknown flag or an unusable value is exit 2, never a default.

Exit codes: 0 packaged (and, with --build, built); 1 packaging or build
failure; 2 bad arguments.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from typing import Optional, Sequence

PLAN_FILE = "update_plan.seeu"
STUB_FILE = "update_plan_embedded.S"
DECIMAL_TU = "update_plan_embedded.cc"
BUILD_SCRIPT = "build.sh"
BINARY = "model_update"

# The four bytes every plan starts with ("SEEU" little-endian; kSeeuMagic in
# source/plan/schema.h). Checked only to refuse embedding a file that is not
# a plan at all — the runtime re-verifies the full seal at load. When P6's
# ABI manifest lands this constant is read from it rather than restated.
PLAN_MAGIC = b"SEEU"

# Apple Silicon pages are 16 KiB; a plan aligned to that is the page-aligned
# blob zero-copy GPU residency (G1b-2) wants, and it costs at most one page
# of padding per package. Every 4 KiB host is aligned a fortiori.
DEFAULT_PAGE_ALIGN = 16384

# The two compile lines the compiler's build.sh template can carry for the
# embedded TU (BuildScript in compiler/backend/trainer/native_emitter.cc;
# test/tool/pack_update_test.py asserts both appear there verbatim). A
# script that lacks the stub line — one a pre-P1 compiler emitted, whose
# only line is the decimal one — gets that one line rewritten, so the packer
# upgrades any unmodified package ever emitted, not only fresh ones.
DECIMAL_COMPILE_LINE = (
    "$CXX $FLAGS -c update_plan_embedded.cc -o update_plan_embedded.o\n")
STUB_COMPILE_LINE = "$CXX -c update_plan_embedded.S -o update_plan_embedded.o\n"

REPORT_SCHEMA = 1


class PackError(Exception):
    """A packaging failure: reported on stderr, exit 1."""


@dataclass
class Options:
    package_dir: str
    build: bool
    cxx: Optional[str]
    page_align: int
    report: Optional[str]


def render_stub(page_align: int) -> str:
    """The .incbin translation unit.

    Preprocessed assembly (.S): the C preprocessor supplies the target's
    symbol prefix (`__USER_LABEL_PREFIX__` is `_` on Mach-O, empty on ELF),
    the width of size_t, and the section spellings (writable data on
    Apple, for the Metal backend's zero-copy plan wrap), so one stub assembles
    on every target the vendored runtime builds for. The size symbol is a
    label difference, never a literal, so re-running the compiler into the
    same directory can never leave a stale size beside fresh bytes.
    """
    plan_file = PLAN_FILE
    return f"""/* Generated by tool/pack_update.py: the compiled Update Plan, spliced
 * into the object file verbatim by the assembler. Defines the two symbols
 * the generated driver (update_main.cc) links against:
 *   const unsigned char kSeemlUpdatePlan[]   the plan bytes, {page_align}-byte
 *                                            (page) aligned
 *   const size_t kSeemlUpdatePlanSize        their count
 * The assembler resolves "{plan_file}" against its working directory, which
 * build.sh sets to the package directory. */
#define SEEML_CAT_(a, b) a##b
#define SEEML_CAT(a, b) SEEML_CAT_(a, b)
#define SEEML_SYM(name) SEEML_CAT(__USER_LABEL_PREFIX__, name)

#if defined(__APPLE__)
    /* __DATA,__data, not __TEXT,__const: the Metal backend (G1b-2) wraps
     * the plan's frozen weights as a zero-copy shared buffer, and Metal
     * leaves read-only pages unreadable from the CPU once wrapped — the
     * embedding gather then faults. What writable pages cost is the
     * page-fault fail-stop against a stray write after load; the runtime
     * re-seals the plan (re-hashes it) before merge and commit, so such a
     * write is still refused before it can ship, and no runtime path
     * writes through a rodata reference by construction (the validator
     * proves every write targets the arena). Other targets keep .rodata;
     * nothing wraps them. */
    .section __DATA,__data
#else
    .section .rodata
#endif

    .globl SEEML_SYM(kSeemlUpdatePlan)
    .balign {page_align}
SEEML_SYM(kSeemlUpdatePlan):
    .incbin "{plan_file}"
SEEML_SYM(kSeemlUpdatePlan_end):

    .globl SEEML_SYM(kSeemlUpdatePlanSize)
    .balign 8
SEEML_SYM(kSeemlUpdatePlanSize):
#if __SIZEOF_SIZE_T__ == 8
    .quad SEEML_SYM(kSeemlUpdatePlan_end) - SEEML_SYM(kSeemlUpdatePlan)
#else
    .long SEEML_SYM(kSeemlUpdatePlan_end) - SEEML_SYM(kSeemlUpdatePlan)
#endif

#if defined(__ELF__)
    .type SEEML_SYM(kSeemlUpdatePlan), %object
    .size SEEML_SYM(kSeemlUpdatePlan), SEEML_SYM(kSeemlUpdatePlan_end) - SEEML_SYM(kSeemlUpdatePlan)
    .type SEEML_SYM(kSeemlUpdatePlanSize), %object
    .size SEEML_SYM(kSeemlUpdatePlanSize), __SIZEOF_SIZE_T__
    /* Data only: tell the linker this object needs no executable stack. */
    .section .note.GNU-stack,"",%progbits
#endif
"""


def check_plan(path: str) -> int:
    """Refuse anything that is not a non-empty plan file; return its size."""
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as f:
            head = f.read(len(PLAN_MAGIC))
    except OSError as e:
        raise PackError(f"cannot read plan '{path}': {e.strerror}") from e
    if size == 0:
        raise PackError(f"plan '{path}' is empty")
    if head != PLAN_MAGIC:
        raise PackError(
            f"'{path}' does not start with the plan magic {PLAN_MAGIC!r}; "
            "is this the update_plan.seeu seeml-update-compile emitted?")
    return size


def write_atomic(path: str, data: bytes, executable: bool = False) -> None:
    """Temp file in the same directory, fsync, then rename over the target —
    a crash mid-write leaves the old file or none, never a torn one (the
    staging pattern the C++ custodian and seeml-bench already use).

    mkstemp creates the temp file 0600; the package is meant to be copied
    and built elsewhere, so the final file gets the ordinary create mode
    (0666, or 0777 for scripts) under the process umask instead."""
    directory = os.path.dirname(path) or "."
    fd, tmp = tempfile.mkstemp(prefix=".pack_update-", dir=directory)
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
            f.flush()
            os.fchmod(f.fileno(), (0o777 if executable else 0o666) & ~_umask())
            os.fsync(f.fileno())
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _umask() -> int:
    """The process umask, which POSIX only exposes by setting it."""
    current = os.umask(0)
    os.umask(current)
    return current


def adapt_build_script(text: str) -> Optional[str]:
    """Return the script rewritten to assemble the stub, or None if it
    already carries the stub's compile line (post-P1 emitters branch on the
    stub's presence). Keyed on the compile line itself, not the file name:
    a script that merely mentions the stub in a comment still compiles the
    decimal TU and must be rewritten.

    Raises PackError when the script is not one seeml-update-compile
    emitted, or was edited since (the decimal line no longer matches):
    rewriting an unknown script would be a silent default."""
    if STUB_COMPILE_LINE in text:
        return None
    if text.count(DECIMAL_COMPILE_LINE) != 1:
        raise PackError(
            f"{BUILD_SCRIPT} is not an unmodified seeml-update-compile build "
            f"script (no line compiling {DECIMAL_TU}); refusing to rewrite "
            f"it — re-emit the package with --no-embed instead")
    return text.replace(DECIMAL_COMPILE_LINE, STUB_COMPILE_LINE)


def run_build(package_dir: str, cxx: Optional[str]) -> float:
    """Run the package's own build.sh from inside the package; return the
    wall seconds it took. Output streams through unchanged."""
    env = dict(os.environ)
    if cxx is not None:
        env["CXX"] = cxx
    started = time.monotonic()
    try:
        rc = subprocess.run(["sh", BUILD_SCRIPT], cwd=package_dir,
                            env=env).returncode
    except OSError as e:
        raise PackError(f"cannot run {BUILD_SCRIPT}: {e.strerror}") from e
    elapsed = time.monotonic() - started
    if rc != 0:
        raise PackError(f"{BUILD_SCRIPT} failed (exit {rc})")
    binary = os.path.join(package_dir, BINARY)
    if not os.access(binary, os.X_OK):
        raise PackError(f"{BUILD_SCRIPT} exited 0 but left no executable "
                        f"'{binary}'")
    return elapsed


def parse_args(argv: Sequence[str]) -> Options:
    parser = argparse.ArgumentParser(
        prog="pack_update.py",
        allow_abbrev=False,
        description="Embed an emitted package's update plan as an .incbin "
                    "assembly stub (replacing the decimal C++ TU) and "
                    "optionally build the package.")
    parser.add_argument("package_dir",
                        help="directory seeml-update-compile emitted "
                             "(contains update_plan.seeu and build.sh)")
    parser.add_argument("--build", action="store_true",
                        help="run the package's build.sh after embedding")
    parser.add_argument("--cxx", metavar="COMPILER", default=None,
                        help="C++ driver for build.sh (sets CXX; default: "
                             "the environment's CXX, else c++)")
    parser.add_argument("--page-align", metavar="BYTES", type=int,
                        default=DEFAULT_PAGE_ALIGN,
                        help=f"alignment of the embedded plan, a power of two "
                             f"in [64, 65536] (default {DEFAULT_PAGE_ALIGN})")
    parser.add_argument("--report", metavar="PATH", default=None,
                        help="write a machine-readable JSON summary")
    args = parser.parse_args(list(argv))

    align = args.page_align
    if align < 64 or align > 65536 or align & (align - 1):
        parser.error(f"--page-align must be a power of two in [64, 65536], "
                     f"got {align}")
    if args.cxx is not None and (args.cxx == "" or args.cxx.startswith("-")):
        parser.error(f"--cxx requires a compiler name, got '{args.cxx}'")
    if not os.path.isdir(args.package_dir):
        parser.error(f"package_dir '{args.package_dir}' is not a directory")
    return Options(package_dir=args.package_dir, build=args.build,
                   cxx=args.cxx, page_align=align, report=args.report)


def pack(opts: Options) -> dict:
    """Embed, adapt build.sh if needed, drop the decimal TU, maybe build.
    Returns the report dictionary."""
    pkg = opts.package_dir
    plan_path = os.path.join(pkg, PLAN_FILE)
    script_path = os.path.join(pkg, BUILD_SCRIPT)
    stub_path = os.path.join(pkg, STUB_FILE)
    decimal_path = os.path.join(pkg, DECIMAL_TU)

    plan_bytes = check_plan(plan_path)

    try:
        with open(script_path, "r", encoding="utf-8") as f:
            script = f.read()
    except OSError as e:
        raise PackError(f"cannot read '{script_path}': {e.strerror}") from e
    adapted = adapt_build_script(script)

    stub = render_stub(opts.page_align)
    try:
        write_atomic(stub_path, stub.encode("utf-8"))
        if adapted is not None:
            write_atomic(script_path, adapted.encode("utf-8"),
                         executable=True)
    except OSError as e:
        raise PackError(f"cannot write into '{pkg}': {e.strerror}") from e

    # The stub supersedes the decimal TU; a package carries exactly one
    # embedded TU, so build.sh's choice is never ambiguous.
    decimal_removed = False
    if os.path.exists(decimal_path):
        try:
            os.unlink(decimal_path)
        except OSError as e:
            raise PackError(
                f"cannot remove '{decimal_path}': {e.strerror}") from e
        decimal_removed = True

    print(f"pack_update: embedded {PLAN_FILE} ({plan_bytes} bytes) as "
          f"{STUB_FILE}, {opts.page_align}-byte aligned", file=sys.stderr)
    if adapted is not None:
        print(f"pack_update: rewrote {BUILD_SCRIPT} (pre-P1 emitter) to "
              f"assemble the stub", file=sys.stderr)
    if decimal_removed:
        print(f"pack_update: removed {DECIMAL_TU} (superseded by the stub)",
              file=sys.stderr)

    build_seconds: Optional[float] = None
    if opts.build:
        build_seconds = run_build(pkg, opts.cxx)
        print(f"pack_update: built {os.path.join(pkg, BINARY)} in "
              f"{build_seconds:.1f} s", file=sys.stderr)

    return {
        "schema": REPORT_SCHEMA,
        "tool": "pack_update",
        "package_dir": pkg,
        "plan_file": plan_path,
        "plan_bytes": plan_bytes,
        "embedded_tu": stub_path,
        "page_align": opts.page_align,
        "build_script_rewritten": adapted is not None,
        "decimal_tu_removed": decimal_removed,
        "built": opts.build,
        "build_seconds": (None if build_seconds is None
                          else round(build_seconds, 3)),
        "binary": os.path.join(pkg, BINARY) if opts.build else None,
    }


def main(argv: Optional[Sequence[str]] = None) -> int:
    opts = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        report = pack(opts)
        if opts.report is not None:
            # A diagnostic, not a package artifact: a plain write, like the
            # compiler's own --report.
            try:
                with open(opts.report, "w", encoding="utf-8") as f:
                    json.dump(report, f, indent=2)
                    f.write("\n")
            except OSError as e:
                raise PackError(
                    f"cannot write report '{opts.report}': {e.strerror}"
                ) from e
    except PackError as e:
        print(f"pack_update: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
