#include "compiler/backend/native_emitter.h"

#include <filesystem>
#include <fstream>

namespace seeml::update {

namespace {

std::expected<void, std::string> WriteFile(const std::string& path,
                                           const std::string& content,
                                           bool executable = false) {
  std::ofstream f(path, std::ios::binary | std::ios::trunc);
  if (!f) return std::unexpected("NativeEmitter: cannot write '" + path + "'");
  f << content;
  if (!f) return std::unexpected("NativeEmitter: short write to '" + path + "'");
  f.close();
  if (executable) {
    std::error_code ec;
    std::filesystem::permissions(path,
                                 std::filesystem::perms::owner_all |
                                     std::filesystem::perms::group_read |
                                     std::filesystem::perms::group_exec |
                                     std::filesystem::perms::others_read |
                                     std::filesystem::perms::others_exec,
                                 ec);
  }
  return {};
}

std::string EmbedPlanAsTU(const std::vector<uint8_t>& plan) {
  std::string tu;
  tu.reserve(plan.size() * 5 + 512);
  tu +=
      "// Generated by seeml-update-compile. The compiled Update Plan as an\n"
      "// object-file byte array: instruction streams, memory layout, frozen\n"
      "// weights, and adapter initialization — the entire update, as data.\n"
      "#include <cstddef>\n\n"
      "extern const unsigned char kSeemlUpdatePlan[] "
      "__attribute__((aligned(64)));\n"
      "extern const size_t kSeemlUpdatePlanSize;\n\n"
      "const unsigned char kSeemlUpdatePlan[] __attribute__((aligned(64))) = "
      "{\n";
  char buf[8];
  for (size_t i = 0; i < plan.size(); ++i) {
    std::snprintf(buf, sizeof(buf), "%u,", plan[i]);
    tu += buf;
    if ((i + 1) % 24 == 0) tu += '\n';
  }
  tu += "\n};\nconst size_t kSeemlUpdatePlanSize = sizeof(kSeemlUpdatePlan);\n";
  return tu;
}

constexpr const char* kMainTU = R"cpp(// Generated by seeml-update-compile.
// The on-device model update program: train LoRA adapters against local
// data, gate on held-out validation, merge deltas, commit durably.
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>

#include "runtime/dataset.h"
#include "runtime/update_engine.h"

extern const unsigned char kSeemlUpdatePlan[];
extern const size_t kSeemlUpdatePlanSize;

namespace {

const char* Arg(int argc, char** argv, const char* flag, const char* dflt) {
  for (int i = 1; i + 1 < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return argv[i + 1];
  return dflt;
}

bool Has(int argc, char** argv, const char* flag) {
  for (int i = 1; i < argc; ++i)
    if (std::strcmp(argv[i], flag) == 0) return true;
  return false;
}

bool ParseU64(const char* s, uint64_t* out) {
  errno = 0;
  char* end = nullptr;
  const unsigned long long v = std::strtoull(s, &end, 10);
  if (errno != 0 || end == s || *end != '\0' || *s == '-') return false;
  *out = v;
  return true;
}

bool ParseF64(const char* s, double* out) {
  errno = 0;
  char* end = nullptr;
  const double v = std::strtod(s, &end);
  if (errno != 0 || end == s || *end != '\0') return false;
  *out = v;
  return true;
}

}  // namespace

int main(int argc, char** argv) {
  const std::string model = Arg(argc, argv, "--model", "");
  const std::string data = Arg(argc, argv, "--data", "");
  const std::string out = Arg(argc, argv, "--out", "updated_model.smf");
  const std::string loss_log = Arg(argc, argv, "--loss-log", "");
  const bool force = Has(argc, argv, "--force");

  uint64_t steps = 0, seed = 0;
  double val_frac = 0.1;
  if (!ParseU64(Arg(argc, argv, "--steps", "0"), &steps) ||
      !ParseU64(Arg(argc, argv, "--seed", "0"), &seed) ||
      !ParseF64(Arg(argc, argv, "--val-frac", "0.1"), &val_frac) ||
      val_frac < 0.0 || val_frac >= 1.0) {
    std::fprintf(stderr, "invalid numeric argument\n");
    return 2;
  }

  if (model.empty() || data.empty()) {
    std::fprintf(stderr,
                 "usage: model_update --model <source.smf> --data <corpus.sds>"
                 " [--out updated.smf] [--steps N] [--seed S]"
                 " [--val-frac F] [--checkpoint ckpt] [--checkpoint-every N]"
                 " [--resume] [--loss-log curve.csv] [--force]\n");
    return 2;
  }

  seeml::update_rt::UpdateEngine engine;
  if (auto r = engine.LoadFromMemory(kSeemlUpdatePlan, kSeemlUpdatePlanSize); !r) {
    std::fprintf(stderr, "load: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr,
               "seeml-update: resource contract — arena %llu bytes"
               " (%llu persistent)\n",
               (unsigned long long)engine.header().arena_size,
               (unsigned long long)engine.header().persistent_size);

  auto dataset = seeml::update_rt::Dataset::LoadFromFile(data);
  if (!dataset) {
    std::fprintf(stderr, "data: %s\n", dataset.error().c_str());
    return 1;
  }

  // Held-out validation split (before shuffling) drives the regression
  // gate; --val-frac 0 falls back to the training-loss trend.
  std::optional<seeml::update_rt::Dataset> val_set;
  if (val_frac > 0.0) {
    auto split = dataset->SplitValidation(val_frac);
    if (!split) {
      std::fprintf(stderr, "data: %s\n", split.error().c_str());
      return 1;
    }
    val_set = std::move(*split);
  }
  dataset->EnableShuffle(seed);

  seeml::update_rt::TrainOptions options;
  options.checkpoint_path = Arg(argc, argv, "--checkpoint", "");
  options.resume = Has(argc, argv, "--resume");
  options.validation = val_set ? &*val_set : nullptr;
  options.record_loss_curve = !loss_log.empty();
  if (!ParseU64(Arg(argc, argv, "--checkpoint-every", "0"),
                &options.checkpoint_every)) {
    std::fprintf(stderr, "invalid --checkpoint-every\n");
    return 2;
  }

  auto report = engine.Train(*dataset, steps, options);
  if (!report) {
    std::fprintf(stderr, "train: %s\n", report.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: train loss %.6f -> %.6f over %llu steps\n",
               report->initial_avg_loss, report->final_avg_loss,
               (unsigned long long)report->steps);
  if (report->has_validation)
    std::fprintf(stderr, "seeml-update: validation loss %.6f -> %.6f\n",
                 report->val_initial_loss, report->val_final_loss);

  if (!loss_log.empty()) {
    std::FILE* f = std::fopen(loss_log.c_str(), "w");
    if (f) {
      std::fprintf(f, "step,loss\n");
      for (size_t i = 0; i < report->loss_curve.size(); ++i)
        std::fprintf(f, "%zu,%.6f\n", i + 1, report->loss_curve[i]);
      std::fclose(f);
    }
  }

  // Regression gate: a failed update must leave the device untouched.
  // With a validation split this gates on held-out loss, not training loss.
  if (!report->improved() && !force) {
    std::fprintf(stderr,
                 "seeml-update: REJECTED — %s loss did not improve; source"
                 " model left untouched (--force to override)\n",
                 report->has_validation ? "validation" : "training");
    return 3;
  }

  if (auto r = engine.RunMerge(); !r) {
    std::fprintf(stderr, "merge: %s\n", r.error().c_str());
    return 1;
  }
  if (auto r = engine.CommitToModel(model, out); !r) {
    std::fprintf(stderr, "commit: %s\n", r.error().c_str());
    return 1;
  }
  std::fprintf(stderr, "seeml-update: committed '%s'\n", out.c_str());
  return 0;
}
)cpp";

// The runtime sources vendored into every emitted package. The package must
// build on a machine (or in a cross-toolchain) that has never seen this
// repository — the compiler host's checkout cannot be a build dependency of
// the deliverable.
constexpr const char* kVendoredSources[] = {
    "runtime/update_engine.h",  "runtime/update_engine.cc",
    "runtime/update_kernels.h", "runtime/update_kernels.cc",
    "runtime/dataset.h",        "runtime/dataset.cc",
    "compiler/backend/update_types.h", "source/hash.h",
};

std::string BuildScript() {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by seeml-update-compile: builds the self-contained\n";
  s += "# `model_update` executable from the vendored runtime sources.\n";
  s += "# Cross-compile by setting CXX to your target toolchain.\n";
  s += "set -e\n";
  s += "cd \"$(dirname \"$0\")\"\n";
  s += "CXX=\"${CXX:-c++}\"\n";
  s += "FLAGS=\"-std=c++23 -O2 -Wall -Wextra -I.\"\n";
  s += "$CXX $FLAGS -c update_plan_embedded.cc -o update_plan_embedded.o\n";
  s += "$CXX $FLAGS -c update_main.cc -o update_main.o\n";
  s += "$CXX $FLAGS -c runtime/update_kernels.cc -o update_kernels.o\n";
  s += "$CXX $FLAGS -c runtime/dataset.cc -o dataset.o\n";
  s += "$CXX $FLAGS -c runtime/update_engine.cc -o update_engine.o\n";
  s += "$CXX update_main.o update_plan_embedded.o update_engine.o dataset.o "
       "update_kernels.o -o model_update\n";
  s += "echo \"built: $(pwd)/model_update\"\n";
  return s;
}

}  // namespace

std::expected<EmitPaths, std::string> EmitNativePackage(
    const std::vector<uint8_t>& plan, const std::string& out_dir,
    const std::string& repo_root) {
  std::error_code ec;
  std::filesystem::create_directories(out_dir, ec);
  if (ec)
    return std::unexpected("NativeEmitter: cannot create '" + out_dir + "'");

  EmitPaths paths{
      .plan_file = out_dir + "/update_plan.seeu",
      .embedded_tu = out_dir + "/update_plan_embedded.cc",
      .main_tu = out_dir + "/update_main.cc",
      .build_script = out_dir + "/build.sh",
  };

  {
    std::ofstream f(paths.plan_file, std::ios::binary | std::ios::trunc);
    if (!f)
      return std::unexpected("NativeEmitter: cannot write plan file");
    f.write(reinterpret_cast<const char*>(plan.data()),
            static_cast<std::streamsize>(plan.size()));
    if (!f)
      return std::unexpected("NativeEmitter: short write to '" +
                             paths.plan_file + "'");
  }
  if (auto r = WriteFile(paths.embedded_tu, EmbedPlanAsTU(plan)); !r)
    return std::unexpected(r.error());
  if (auto r = WriteFile(paths.main_tu, kMainTU); !r)
    return std::unexpected(r.error());

  // Vendor the runtime into the package so it builds without the repo.
  for (const char* rel : kVendoredSources) {
    const auto src = std::filesystem::path(repo_root) / rel;
    const auto dst = std::filesystem::path(out_dir) / rel;
    std::filesystem::create_directories(dst.parent_path(), ec);
    if (ec)
      return std::unexpected("NativeEmitter: cannot create '" +
                             dst.parent_path().string() + "'");
    std::filesystem::copy_file(
        src, dst, std::filesystem::copy_options::overwrite_existing, ec);
    if (ec)
      return std::unexpected("NativeEmitter: cannot vendor '" + src.string() +
                             "' (" + ec.message() + ")");
  }

  if (auto r = WriteFile(paths.build_script, BuildScript(),
                         /*executable=*/true);
      !r)
    return std::unexpected(r.error());

  return paths;
}

}  // namespace seeml::update
